CREATE TABLE YELP_USER (
YELP_ID VARCHAR(20) PRIMARY KEY,
EMAIL VARCHAR(50),
FIRST_NAME VARCHAR(40),
LAST_NAME VARCHAR(40),
DOB VARCHAR(20),
BIRTH_PLACE VARCHAR(40),
GENDER VARCHAR(20),
FRIENDLIST VARCHAR(50),
COMPLIMENTED_FRIENDLIST VARCHAR (50),
CHECKEDIN_BUSINESS VARCHAR(60)
);

INSERT INTO YELP_USER VALUES ('YI', 'john@yahoo.com', 'John', 'Smith', '12/12/1992', 'FL', 'M', 'Y2, Y7,Y9', 'Y7,Y9', 'B3, B2, B13, B35, B36, B5, B4, B9');

CREATE TABLE REVIEWS(
    REVIEW_ID VARCHAR(20) PRIMARY KEY,
    STARS INTEGER(5),
    PUBLISH_DATE DATE,
    FOREIGN KEY (BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID),
    LIST_OF_COMMENTS VARCHAR(60)
    FOREIGN KEY (AUTHOR) REFERENCES YELP_USER(YELP_ID)
);

CREATE TABLE IF NOT EXISTS BUSINESS(
    BUSINESS_ID INTEGER (250) PRIMARY KEY,
    BUSINESS_NAME VARCHAR(250),
    DAYS_OF_OPERATION VARCHAR(40),
    AMBIENT_TYPE VARCHAR(40),
    Address VARCHAR(250),
    FOREIGN KEY (BUSINESS_CATEGORY) REFERENCES BUSINESS_CATEGORY(BUSINESS_CATEGORY_ID 
);

CREATE TABLE IF NOT EXISTS BUSINESS_CATEGORY(
    BUSINESS_CATEGORY_ID VARCHAR(250),
    BUSINESS_CATEGORY_NAME VARCHAR(250),
    LIST_OF_SUBCATEGORIES VARCHAR (250)
);

CREATE TABLE IF NOT EXISTS CHECKIN(
    ID INTEGER(50),
    INFO VARCHAR(250),
    FOREIGN KEY (BUSN_ID) REFERENCES BUSINESS(BUSINESS_ID)
);

